language: haskell

before_install:
  - cabal update
  - cabal install cpphs-1.19.3
  - cabal install happy alex
  - cabal install Agda
  - agda --version

install: true

script:
  - git clone https://github.com/HoTT/HoTT-Agda.git
  - agda -i. -i./HoTT-Agda README.agda
